// <auto-generated />
using System;
using AITasker_Modular.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AITasker_Modular.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260610093932_AddAICategoryDomainsTable")]
    partial class AddAICategoryDomainsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.AICategoryDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AICategoryDomains");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.AICategoryDomainExpertProfile", b =>
                {
                    b.Property<Guid>("AICategoryDomainsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpertProfilesUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AICategoryDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpertProfileUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AICategoryDomainsId", "ExpertProfilesUserId");

                    b.HasIndex("AICategoryDomainId");

                    b.HasIndex("ExpertProfileUserId");

                    b.ToTable("AICategoryDomainExpertProfile");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.ExpertProfileSkill", b =>
                {
                    b.Property<Guid>("ExpertProfilesUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExpertProfilesUserId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ExpertProfileSkill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginJobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OriginJobPostId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.TransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWalletId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceWalletId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AICategoryDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deadline")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AICategoryDomainId");

                    b.HasIndex("ClientId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPostSkill", b =>
                {
                    b.Property<Guid>("JobPostsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobPostsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("JobPostSkill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UseCaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.ToTable("JobRequirements");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("JobPostId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.MiniTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FeedbackSenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackSenderId");

                    b.HasIndex("TaskId");

                    b.ToTable("MiniTasks");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EscrowBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("JobPostId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.ProjectSkill", b =>
                {
                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ProjectSkill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ExpertProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReputationCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.ToTable("ExpertProfiles");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.Wallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.AICategoryDomainExpertProfile", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.AICategoryDomain", "AICategoryDomain")
                        .WithMany()
                        .HasForeignKey("AICategoryDomainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.UserModule.ExpertProfile", "ExpertProfile")
                        .WithMany()
                        .HasForeignKey("ExpertProfileUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AICategoryDomain");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.ExpertProfileSkill", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ExpertProfile", "ExpertProfile")
                        .WithMany("ExpertProfileSkills")
                        .HasForeignKey("ExpertProfilesUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Skill", "Skill")
                        .WithMany("ExpertProfileSkills")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExpertProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Conversation", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "OriginJobPost")
                        .WithMany()
                        .HasForeignKey("OriginJobPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("Expert");

                    b.Navigation("OriginJobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Message", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.ChatModule.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.Review", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.TransactionLog", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.Wallet", "DestinationWallet")
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.UserModule.Wallet", "SourceWallet")
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DestinationWallet");

                    b.Navigation("Project");

                    b.Navigation("SourceWallet");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPost", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.AICategoryDomain", "AICategoryDomain")
                        .WithMany()
                        .HasForeignKey("AICategoryDomainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "ClientUser")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AICategoryDomain");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPostSkill", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("JobPostsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Skill", "Skill")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobRequirement", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.Proposal", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.MiniTask", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "FeedbackSender")
                        .WithMany()
                        .HasForeignKey("FeedbackSenderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FeedbackSender");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Project", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.ChatModule.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("Conversation");

                    b.Navigation("Expert");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.ProjectSkill", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Task", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ExpertProfile", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AITasker_Modular.Modules.UserModule.ExpertProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.Wallet", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AITasker_Modular.Modules.UserModule.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Skill", b =>
                {
                    b.Navigation("ExpertProfileSkills");

                    b.Navigation("JobPostSkills");

                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPost", b =>
                {
                    b.Navigation("JobPostSkills");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Project", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ExpertProfile", b =>
                {
                    b.Navigation("ExpertProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
