// <auto-generated />
using System;
using AITasker_Modular.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AITasker_Modular.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AITasker_Modular.Database.ProposalAiChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AiResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("JobPostId");

                    b.ToTable("ProposalAiChats");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.DomainExpertProfile", b =>
                {
                    b.Property<Guid>("DomainId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ExpertProfilesUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("DomainId", "ExpertProfilesUserId");

                    b.HasIndex("ExpertProfilesUserId");

                    b.ToTable("DomainExpertProfiles");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.ExpertProfileSkill", b =>
                {
                    b.Property<Guid>("ExpertProfilesUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("char(36)");

                    b.HasKey("ExpertProfilesUserId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ExpertProfileSkill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OriginJobPostId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OriginJobPostId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.DisputeModule.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientEvidenceUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EvidenceDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpertEvidenceUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("HandlerStaffId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResolutionVerdict")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HandlerStaffId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.DisputeModule.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("HandlerStaffId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HandlerStaffId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.TransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DestinationWalletId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceWalletId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWalletId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceWalletId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Deadline")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DurationUnit")
                        .HasColumnType("longtext");

                    b.Property<int>("DurationValue")
                        .HasColumnType("int");

                    b.Property<Guid?>("SpecializationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DomainId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPostSkill", b =>
                {
                    b.Property<Guid>("JobPostsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("char(36)");

                    b.HasKey("JobPostsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("JobPostSkill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UseCaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.ToTable("JobRequirements");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Portfolio")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("JobPostId", "ExpertId")
                        .IsUnique();

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.MiniTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackContent")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FeedbackSenderId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackSenderId");

                    b.HasIndex("TaskId");

                    b.ToTable("MiniTasks");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EscrowBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("JobPostId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProjectLink")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("JobPostId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.ProjectSkill", b =>
                {
                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjectsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ProjectSkill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FeedbackContent")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FeedbackSenderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackSenderId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AppointedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ExpertProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Certifications")
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PortfolioUrls")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ReputationCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double");

                    b.HasKey("UserId");

                    b.ToTable("ExpertProfiles");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.Wallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("AITasker_Modular.Database.ProposalAiChat", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.DomainExpertProfile", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ExpertProfile", "ExpertProfile")
                        .WithMany()
                        .HasForeignKey("ExpertProfilesUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.ExpertProfileSkill", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ExpertProfile", "ExpertProfile")
                        .WithMany("ExpertProfileSkills")
                        .HasForeignKey("ExpertProfilesUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Skill", "Skill")
                        .WithMany("ExpertProfileSkills")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExpertProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Specialization", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Domain", "Domain")
                        .WithMany("Specializations")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Conversation", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "OriginJobPost")
                        .WithMany()
                        .HasForeignKey("OriginJobPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("Expert");

                    b.Navigation("OriginJobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ChatModule.Message", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.ChatModule.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.DisputeModule.Dispute", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "HandlerStaff")
                        .WithMany()
                        .HasForeignKey("HandlerStaffId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HandlerStaff");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.DisputeModule.Report", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "HandlerStaff")
                        .WithMany()
                        .HasForeignKey("HandlerStaffId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HandlerStaff");

                    b.Navigation("Project");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.Review", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.InteractionModule.TransactionLog", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.Wallet", "DestinationWallet")
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.UserModule.Wallet", "SourceWallet")
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DestinationWallet");

                    b.Navigation("Project");

                    b.Navigation("SourceWallet");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPost", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "ClientUser")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ClientUser");

                    b.Navigation("Domain");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPostSkill", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("JobPostsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Skill", "Skill")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobRequirement", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany("JobRequirements")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.Proposal", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.MiniTask", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "FeedbackSender")
                        .WithMany()
                        .HasForeignKey("FeedbackSenderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Task", "Task")
                        .WithMany("MiniTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FeedbackSender");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Project", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.ChatModule.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.JobModule.JobPost", "JobPost")
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("Conversation");

                    b.Navigation("Expert");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.ProjectSkill", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AITasker_Modular.Modules.CategoryTagModule.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Task", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", "FeedbackSender")
                        .WithMany()
                        .HasForeignKey("FeedbackSenderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AITasker_Modular.Modules.ProjectModule.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FeedbackSender");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ExpertProfile", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AITasker_Modular.Modules.UserModule.ExpertProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.Wallet", b =>
                {
                    b.HasOne("AITasker_Modular.Modules.UserModule.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AITasker_Modular.Modules.UserModule.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Domain", b =>
                {
                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.CategoryTagModule.Skill", b =>
                {
                    b.Navigation("ExpertProfileSkills");

                    b.Navigation("JobPostSkills");

                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.JobModule.JobPost", b =>
                {
                    b.Navigation("JobPostSkills");

                    b.Navigation("JobRequirements");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Project", b =>
                {
                    b.Navigation("ProjectSkills");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.ProjectModule.Task", b =>
                {
                    b.Navigation("MiniTasks");
                });

            modelBuilder.Entity("AITasker_Modular.Modules.UserModule.ExpertProfile", b =>
                {
                    b.Navigation("ExpertProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
