// MOCK DB ONLY - delete this file/folder when real backend is connected

export const projects = [
  // ==================== CLIENT-001 PROJECTS (10) ====================
  {
    id: "proj-001", clientId: "client-001", assignedExpertId: null,
    title: "AI-Powered Medical Chatbot for Patient Triage",
    description: "Build an NLP chatbot that can triage patient symptoms and recommend appropriate care levels. Must integrate with our existing EHR system via HL7 FHIR.",
    category: "nlp-chatbots", budget: 15000, durationValue: 8, durationUnit: "weeks",
    requiredSkills: ["Python", "NLP", "Healthcare", "HL7 FHIR", "FastAPI"],
    status: "open", createdAt: "2026-05-01T10:00:00Z", deadline: "2026-07-15T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-002", clientId: "client-001", assignedExpertId: "expert-001",
    title: "Chest X-Ray Classification Model",
    description: "Develop a CNN-based deep learning model to classify chest X-rays for 14 common pathologies. Needs 95%+ accuracy on test set. Deployable as a REST API.",
    category: "computer-vision", budget: 22000, durationValue: 12, durationUnit: "weeks",
    requiredSkills: ["Python", "PyTorch", "Computer Vision", "DICOM", "AWS"],
    status: "in_progress", createdAt: "2026-03-15T08:00:00Z", deadline: "2026-06-15T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-003", clientId: "client-001", assignedExpertId: "expert-001",
    title: "Patient Readmission Risk Prediction",
    description: "Build an ML model to predict 30-day readmission risk using patient history, demographics, and clinical data. Integrate with our analytics dashboard.",
    category: "ml-analytics", budget: 18000, durationValue: 10, durationUnit: "weeks",
    requiredSkills: ["Python", "Scikit-learn", "XGBoost", "SQL", "Tableau"],
    status: "completed", createdAt: "2026-01-10T12:00:00Z", deadline: "2026-03-25T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-004", clientId: "client-001", assignedExpertId: null,
    title: "Automated Insurance Claim Processing Agent",
    description: "Create an AI agent that automates insurance claim intake, validation, and routing. Must reduce manual processing by 70% and integrate with our claims management system.",
    category: "ai-automation-agents", budget: 28000, durationValue: 16, durationUnit: "weeks",
    requiredSkills: ["Python", "LangChain", "OCR", "RPA", "API Integration"],
    status: "open", createdAt: "2026-05-10T09:00:00Z", deadline: "2026-09-01T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-005", clientId: "client-001", assignedExpertId: "expert-002",
    title: "Clinical Notes NLP Pipeline",
    description: "Build an NLP pipeline to extract structured data (diagnoses, medications, procedures) from unstructured clinical notes. Must handle 50K+ notes daily.",
    category: "nlp-chatbots", budget: 20000, durationValue: 10, durationUnit: "weeks",
    requiredSkills: ["Python", "spaCy", "Transformers", "NER", "PostgreSQL"],
    status: "in_progress", createdAt: "2026-04-01T07:00:00Z", deadline: "2026-06-20T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-006", clientId: "client-001", assignedExpertId: "expert-002",
    title: "Medical Image Segmentation Tool",
    description: "Develop a deep learning tool for automated organ segmentation in CT scans. Must achieve Dice score >0.90 on test dataset.",
    category: "computer-vision", budget: 25000, durationValue: 14, durationUnit: "weeks",
    requiredSkills: ["Python", "PyTorch", "UNet", "Medical Imaging", "Docker"],
    status: "completed", createdAt: "2026-02-01T10:00:00Z", deadline: "2026-05-01T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-007", clientId: "client-001", assignedExpertId: null,
    title: "Healthcare Analytics Dashboard",
    description: "Build an interactive analytics dashboard for tracking patient outcomes, operational metrics, and cost analysis. Must support real-time data updates.",
    category: "ml-analytics", budget: 16000, durationValue: 8, durationUnit: "weeks",
    requiredSkills: ["Python", "Dash", "Plotly", "PostgreSQL", "Redis"],
    status: "open", createdAt: "2026-05-20T11:00:00Z", deadline: "2026-07-20T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-008", clientId: "client-001", assignedExpertId: "expert-001",
    title: "AI-Powered Appointment Scheduling Agent",
    description: "Create an AI scheduling agent that handles appointment booking, rescheduling, and reminders via chat and voice interfaces.",
    category: "ai-automation-agents", budget: 12000, durationValue: 6, durationUnit: "weeks",
    requiredSkills: ["Python", "LangChain", "Twilio", "Google Calendar API", "FastAPI"],
    status: "in_progress", createdAt: "2026-04-20T08:00:00Z", deadline: "2026-06-10T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-009", clientId: "client-001", assignedExpertId: null,
    title: "Symptom Checker Chatbot for Website",
    description: "Build a customer-facing symptom checker chatbot for our website. Must be multilingual (EN+ES) and HIPAA compliant.",
    category: "nlp-chatbots", budget: 10000, durationValue: 6, durationUnit: "weeks",
    requiredSkills: ["Python", "Rasa", "FastAPI", "React", "HIPAA Compliance"],
    status: "cancelled", createdAt: "2026-03-01T09:00:00Z", deadline: "2026-04-30T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-010", clientId: "client-001", assignedExpertId: null,
    title: "Pathology Slide AI Classifier",
    description: "Develop an AI model to classify pathology slides for cancer detection. Must achieve pathologist-level accuracy on validation set.",
    category: "computer-vision", budget: 35000, durationValue: 20, durationUnit: "weeks",
    requiredSkills: ["Python", "PyTorch", "Digital Pathology", "WSI", "DICOM"],
    status: "open", createdAt: "2026-05-25T10:00:00Z", deadline: "2026-10-15T00:00:00Z", attachmentUrls: [],
  },

  // ==================== CLIENT-002 PROJECTS (10) ====================
  {
    id: "proj-011", clientId: "client-002", assignedExpertId: null,
    title: "Fraud Detection Model for Credit Card Transactions",
    description: "Build a real-time fraud detection model for credit card transactions. Must handle 10K+ TPS with <0.1% false positive rate.",
    category: "ml-analytics", budget: 30000, durationValue: 12, durationUnit: "weeks",
    requiredSkills: ["Python", "XGBoost", "Spark", "Kafka", "GCP"],
    status: "open", createdAt: "2026-05-05T08:00:00Z", deadline: "2026-08-01T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-012", clientId: "client-002", assignedExpertId: "expert-002",
    title: "Automated KYC Document Verification Agent",
    description: "Create an AI agent pipeline that automates KYC document verification using OCR, face matching, and fraud checks. Must integrate with our compliance platform.",
    category: "ai-automation-agents", budget: 25000, durationValue: 10, durationUnit: "weeks",
    requiredSkills: ["Python", "OCR", "Face Recognition", "LangChain", "AWS Textract"],
    status: "in_progress", createdAt: "2026-04-01T10:00:00Z", deadline: "2026-06-15T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-013", clientId: "client-002", assignedExpertId: "expert-001",
    title: "Customer Support RAG Chatbot",
    description: "Build a RAG-based customer support chatbot trained on our product docs, FAQs, and support tickets. Must handle 5K+ concurrent users.",
    category: "nlp-chatbots", budget: 20000, durationValue: 8, durationUnit: "weeks",
    requiredSkills: ["Python", "LangChain", "Vector DB", "OpenAI API", "Kubernetes"],
    status: "completed", createdAt: "2025-12-01T09:00:00Z", deadline: "2026-02-01T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-014", clientId: "client-002", assignedExpertId: "expert-001",
    title: "Check Fraud Detection with Computer Vision",
    description: "Develop a computer vision system to detect fraudulent checks using image analysis. Must classify check features and flag anomalies.",
    category: "computer-vision", budget: 18000, durationValue: 8, durationUnit: "weeks",
    requiredSkills: ["Python", "OpenCV", "PyTorch", "AWS SageMaker", "Docker"],
    status: "in_progress", createdAt: "2026-04-15T08:00:00Z", deadline: "2026-06-15T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-015", clientId: "client-002", assignedExpertId: null,
    title: "Credit Risk Scoring Model",
    description: "Build an ML-based credit risk scoring model using alternative data sources. Must be explainable (SHAP/LIME) and comply with fair lending regulations.",
    category: "ml-analytics", budget: 22000, durationValue: 10, durationUnit: "weeks",
    requiredSkills: ["Python", "XGBoost", "SHAP", "SQL", "MLflow"],
    status: "open", createdAt: "2026-05-15T07:00:00Z", deadline: "2026-07-30T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-016", clientId: "client-002", assignedExpertId: "expert-002",
    title: "Automated Trading Signal Agent",
    description: "Create an AI agent that generates trading signals from market data, news sentiment, and technical indicators. Must backtest against 5 years of historical data.",
    category: "ai-automation-agents", budget: 35000, durationValue: 16, durationUnit: "weeks",
    requiredSkills: ["Python", "LangChain", "Time Series", "Redis", "WebSockets"],
    status: "completed", createdAt: "2026-01-15T11:00:00Z", deadline: "2026-05-01T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-017", clientId: "client-002", assignedExpertId: "expert-002",
    title: "Financial Document Q&A Chatbot",
    description: "Build a chatbot that answers questions about financial documents (10-K, 10-Q, earnings reports). Must use RAG with proper citation of sources.",
    category: "nlp-chatbots", budget: 15000, durationValue: 6, durationUnit: "weeks",
    requiredSkills: ["Python", "LangChain", "Pinecone", "Streamlit", "OpenAI API"],
    status: "in_progress", createdAt: "2026-05-01T09:00:00Z", deadline: "2026-06-20T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-018", clientId: "client-002", assignedExpertId: null,
    title: "Receipt Scanner and Expense Categorizer",
    description: "Build a mobile-ready receipt scanner with OCR that auto-categorizes expenses. Must support 20+ languages and handle crumpled receipts.",
    category: "computer-vision", budget: 12000, durationValue: 8, durationUnit: "weeks",
    requiredSkills: ["Python", "Tesseract OCR", "MobileNet", "React Native", "FastAPI"],
    status: "cancelled", createdAt: "2026-02-15T08:00:00Z", deadline: "2026-04-15T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-019", clientId: "client-002", assignedExpertId: null,
    title: "Anti-Money Laundering Transaction Monitor",
    description: "Develop an ML system to detect suspicious transaction patterns for AML compliance. Must generate SAR reports automatically.",
    category: "ml-analytics", budget: 40000, durationValue: 18, durationUnit: "weeks",
    requiredSkills: ["Python", "Graph Neural Nets", "Spark", "Neo4j", "Kubernetes"],
    status: "open", createdAt: "2026-05-20T12:00:00Z", deadline: "2026-10-01T00:00:00Z", attachmentUrls: [],
  },
  {
    id: "proj-020", clientId: "client-002", assignedExpertId: "expert-001",
    title: "Algorithmic Trading Backtesting Platform",
    description: "Build a scalable backtesting platform for algorithmic trading strategies. Must support custom indicators, walk-forward optimization, and performance reporting.",
    category: "ml-analytics", budget: 28000, durationValue: 12, durationUnit: "weeks",
    requiredSkills: ["Python", "Pandas", "NumPy", "Plotly", "PostgreSQL"],
    status: "completed", createdAt: "2025-11-01T10:00:00Z", deadline: "2026-02-01T00:00:00Z", attachmentUrls: [],
  },
];
